Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 25, in <module>
    print(temp)
NameError: name 'temp' is not defined
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 25, in <module>
    print(temp)
NameError: name 'temp' is not defined
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 27, in <module>
    Bin(255)
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 15, in Bin
    while t:
UnboundLocalError: local variable 't' referenced before assignment
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 27, in <module>
    toBin(255)
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 15, in toBin
    while t:
UnboundLocalError: local variable 't' referenced before assignment
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
111111110
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
11111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 28, in <module>
    print(toBin(2))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 25, in toBin
    temp = int(("").join(list2))
ValueError: invalid literal for int() with base 10: ''
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
0
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 26, in <module>
    print(toBin(2))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 23, in toBin
    temp = int(("").join(list2.reverse()))
TypeError: can only join an iterable
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 26, in <module>
    print(toBin(255))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 23, in toBin
    temp = int(("").join(list2.reverse()))
TypeError: can only join an iterable
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
11111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
0
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
0
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 27, in <module>
    print(toBin(4))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 24, in toBin
    temp = int(("").join(list2))
ValueError: invalid literal for int() with base 10: ''
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 27, in <module>
    print(toBin(255))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 24, in toBin
    temp = int(("").join(list2))
ValueError: invalid literal for int() with base 10: ''
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 28, in <module>
    print(toBin(2))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 25, in toBin
    temp = int(list3)
ValueError: invalid literal for int() with base 10: ''
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
Traceback (most recent call last):
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 27, in <module>
    print(toBin(2))
  File "D:\@python\Practice\练习17-欧几里得算法.py", line 24, in toBin
    temp = int(("").join(list2))
ValueError: invalid literal for int() with base 10: ''
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================


>>> 
=========================================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================


>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
[]


>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
10
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
11111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
100
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
1
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
11111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
<class 'int'>
1111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
<class 'str'>
01111111
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
<class 'str'>
01
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
<class 'str'>
010
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
[1, 0]
<class 'str'>
01
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
[1, 0]
<class 'str'>
01
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
[1]
[1, 0]
[1, 0]
<class 'str'>
01
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
[0]
[0, 1]
[0, 1]
<class 'str'>
10
>>> 
================== RESTART: D:\@python\Practice\练习17-欧几里得算法.py =================
12
=========================
11111111
>>> 
====================== RESTART: D:/@python/Practice/asd.py =====================
>>> help(test)
Help on function test in module __main__:

test()
    这是一个函数文档

>>> 
====================== RESTART: D:/@python/Practice/asd.py =====================
>>> help(test)
Help on function test in module __main__:

test()
    这是一个函数文档

>>> 
====================== RESTART: D:/@python/Practice/asd.py =====================
>>> 
====================== RESTART: D:/@python/Practice/asd.py =====================
ysx是猪
>>> 
====================== RESTART: D:/@python/Practice/asd.py =====================
lxy是猪
>>> print(range(0))
range(0, 0)
>>> for i in range(0)
SyntaxError: invalid syntax
>>> for i in range(0):
	print(i)

	
>>> 
>>> 
=============== RESTART: D:/@python/Practice/练习18字字符在父字符出现次数统计.py ==============
Traceback (most recent call last):
  File "D:/@python/Practice/练习18字字符在父字符出现次数统计.py", line 16, in <module>
    finder(desStr,subStr)
NameError: name 'finder' is not defined
>>> 
=============== RESTART: D:/@python/Practice/练习18字字符在父字符出现次数统计.py ==============
Traceback (most recent call last):
  File "D:/@python/Practice/练习18字字符在父字符出现次数统计.py", line 16, in <module>
    findstr(desStr,subStr)
  File "D:/@python/Practice/练习18字字符在父字符出现次数统计.py", line 12, in findstr
    print("子字符串在父字符穿中出现的次数为：{}".fomat(count))
AttributeError: 'str' object has no attribute 'fomat'
>>> 
=============== RESTART: D:/@python/Practice/练习18字字符在父字符出现次数统计.py ==============
子字符串在父字符穿中出现的次数为：3
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
1
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
1
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/safaf.py", line 6, in <module>
    test1(count)
  File "D:/@python/Practice/safaf.py", line 3, in test1
    count += a
UnboundLocalError: local variable 'count' referenced before assignment
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
1
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
第四个 2
1
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/safaf.py", line 13, in <module>
    test1(count)
TypeError: test1() takes 0 positional arguments but 1 was given
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
第四个 2
2
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/safaf.py", line 14, in <module>
    test1()
  File "D:/@python/Practice/safaf.py", line 5, in test1
    test2(count)
TypeError: test2() takes 0 positional arguments but 1 was given
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
第四个 3
3
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/safaf.py", line 14, in <module>
    test1()
  File "D:/@python/Practice/safaf.py", line 5, in test1
    test2()
  File "D:/@python/Practice/safaf.py", line 10, in test2
    print(count)
UnboundLocalError: local variable 'count' referenced before assignment
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/safaf.py", line 14, in <module>
    test1()
  File "D:/@python/Practice/safaf.py", line 5, in test1
    test2()
TypeError: test2() missing 1 required positional argument: 'count'
>>> 
===================== RESTART: D:/@python/Practice/safaf.py ====================
2
3
第四个 2
2
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/练习19-2.py", line 9, in <module>
    palindrome("海上自来水来自上海")
  File "D:/@python/Practice/练习19-2.py", line 2, in palindrome
    list1 = string.split("")
ValueError: empty separator
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
海上自来水来自上海
Traceback (most recent call last):
  File "D:/@python/Practice/练习19-2.py", line 10, in <module>
    palindrome("海上自来水来自上海")
  File "D:/@python/Practice/练习19-2.py", line 3, in palindrome
    list1 = string.split("")
ValueError: empty separator
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
这是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
这是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
Traceback (most recent call last):
  File "D:/@python/Practice/练习19-2.py", line 9, in <module>
    palindrome("海上自来水来自上海")
  File "D:/@python/Practice/练习19-2.py", line 5, in palindrome
    lis
NameError: name 'lis' is not defined
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海上自来水来自上海']
这是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海', '上', '自', '来', '水', '来', '自', '上', '海']
这是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海', '上', '自', '来', '水', '来', '自', '上']
这不是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海', '上', '自', '来', '水', '来', '自', '上']
这不是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海', '上', '自', '来', '水', '来', '自', '上', '海']
这是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
<list_reverseiterator object at 0x0000017760636640>
这不是一个回文联
>>> 
==================== RESTART: D:/@python/Practice/练习19-2.py ====================
['海', '上', '自', '来', '水', '来', '自', '上', '海']
这是一个回文联
>>> 
================= RESTART: D:/@python/Practice/练习19字符串字符类型统计.py ================
第 1 个字符串中有英文 8 个,数字 0 个,空格 2 个,其他字符 0 个
第 2 个字符串中有英文 5 个,数字 0 个,空格 0 个,其他字符 1 个
>>> 
================= RESTART: D:/@python/Practice/练习19字符串字符类型统计.py ================
第 1 个字符串中有英文 8 个,数字 1 个,空格 2 个,其他字符 0 个
第 2 个字符串中有英文 5 个,数字 0 个,空格 0 个,其他字符 1 个
>>> 
================= RESTART: D:/@python/Practice/练习19字符串字符类型统计.py ================
第 1 个字符串中有英文 8 个,数字 1 个,空格 2 个,其他字符 0 个
第 2 个字符串中有英文 9 个,数字 0 个,空格 2 个,其他字符 1 个
>>> 
=================== RESTART: D:/@python/Practice/asda sfad.py ==================
1
>>> 
=================== RESTART: D:/@python/Practice/asda sfad.py ==================
1
2
>>> 
=================== RESTART: D:/@python/Practice/asda sfad.py ==================
2
>>> 
=================== RESTART: D:/@python/Practice/asda sfad.py ==================
2
2
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
6
6
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
6
6
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
7
8
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
6
6
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
7
8
>>> 
===================== RESTART: D:/@python/Practice/FDGFH.py ====================
6
6
6
>>> 
================== RESTART: D:/@python/Practice/练习20统计字符次数.py ==================
Traceback (most recent call last):
  File "D:/@python/Practice/练习20统计字符次数.py", line 4, in <module>
    countStr(str1)
NameError: name 'countStr' is not defined
>>> 
================== RESTART: D:/@python/Practice/练习20统计字符次数.py ==================
Traceback (most recent call last):
  File "D:/@python/Practice/练习20统计字符次数.py", line 4, in <module>
    countStr(str1)
NameError: name 'countStr' is not defined
>>> 
================== RESTART: D:/@python/Practice/练习20统计字符次数.py ==================
李 1
心 1
怡 1
是 3
猪 1
么 1
？ 1
我 2
觉 1
得 1
她 3
， 2
可 1
偏 1
说 1
自 1
己 1
不 1
。 2
\n 1
只 1
能 1
再 1
次 1
劝 1
服 1
了 1
唉 1
>>> 
==================== RESTART: D:/@python/Practice/练习20-2.py ====================
>>> 
==================== RESTART: D:/@python/Practice/练习20-2.py ====================
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 sx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysxx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysxx
>>> 
================ RESTART: D:/@python/Practice/练习20-2.py ===============
密码是 ysxx
>>> 